# Storage Class
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: storageclasses.addons.sigs.k8s.io
spec:
  group: addons.sigs.k8s.io
  names:
    kind: StorageClass
    plural: storageclasses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: storageclass-operator-role
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - addons.sigs.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageclass-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageclass-operator-role
subjects:
- kind: ServiceAccount
  name: storageclass-operator
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageclass-operator
  namespace: kube-system
  labels:
    control-plane: storageclass-operator
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: storageclass-operator
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        control-plane: storageclass-operator
        controller-tools.k8s.io: "1.0"
    spec:
      serviceAccountName: storageclass-operator
      containers:
      - command:
        - /root/manager
        # TODO gcr.io/cluster-api-provider-gcp
        image: gcr.io/jrjohnson-gke/storageclass-operator:latest
        imagePullPolicy: Always
        name: storageclass-operator
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SECRET_NAME
            value: $(WEBHOOK_SECRET_NAME)
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-secret
  namespace: kube-system
---
apiVersion: addons.sigs.k8s.io/v1alpha1
kind: StorageClass
metadata:
  name: default
  namespace: kube-system